version: '3.8'

services:
  client:
    container_name: client
    build:
      context: ./client
    command: npm run start
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '4200:4200'

  gateway:
    container_name: gateway
    build:
      context: ./server/gateway
      target: development
    volumes:
      - ./server/gateway:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '5000:5000'
    command: npm run start:dev
    env_file:
      - ./server/gateway/.env
    depends_on:
      - redis

  users:
    container_name: users
    hostname: users
    build:
      context: ./server/services/users
      target: development
    volumes:
      - ./server/services/users:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '5002:5002'
    command: npm run start:dev
    env_file:
      - ./server/services/users/.env
    depends_on:
      - redis
      - usersdb

  mail:
    container_name: mail
    hostname: mail
    build:
      context: ./server/services/mail
      target: development
    volumes:
      - ./server/services/mail:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '5001:5001'
    command: npm run start:dev
    env_file:
      - ./server/services/mail/.env
    depends_on:
      - redis

  redis:
    container_name: redis

    image: redis:5
    ports:
      - 6379:6379
