version: '3.8'

services:
  frontend:
    container_name: frontend
    build:
      context: ./client
    command: npm run start
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '4200:4200'
    depends_on:
      - backend

  backend:
    container_name: backend
    build:
      context: ./server
      target: development
    ports:
      - '8080:8080'
    command: npm run start:dev
    env_file:
      - ./server/.env
